M48
; DRILL file {KiCad 7.0.7} date Fri Dec  1 19:11:36 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-01T19:11:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X203.315Y-64.12
X208.165Y-64.12
T2
X203.015Y-61.09
X208.465Y-61.09
T3
X165.46Y-117.66
X166.54Y-56.34
T4
X159.0Y-85.65
T0
M30
