M48
; DRILL file {KiCad (6.0.0)} date Thu Jul 21 12:24:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-21T12:24:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X203.315Y-64.12
X208.165Y-64.12
T2
X203.015Y-61.09
X208.465Y-61.09
T3
X165.46Y-117.66
X166.54Y-56.34
T4
X159.0Y-85.65
T0
M30
